language: csharp
mono: none
dotnet: 2.0.0
solution: ApiLibs.sln
matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
    - os: osx
      osx_image: xcode7.2 # macOS 10.11
script:
  - dotnet build
